### ISSUE TITLE
Implement Flesch reading-ease test

### ISSUE THREAD

**Issue by kristiank** [estnltk/estnltk#101]
There exists many reading-ease tests that calculate how easy it is to "read" and "understand" a text. [Flesch](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests#Flesch_reading_ease) is one of the most popular.

I have used EstNLTK for calculating the needed variables for the Flesch reading ease score. I wold now want to implement this as a feature of EstNLTK. What are my options, should I concentrate on version 1.4 or 1.6? Is there documentation meant for module implementers for EstNLTK somewhere?

**Comment by kristiank** [comment]
Since the reading-ease score applies to either sentences or whole texts, one could imagine also tagging the score on the sentence and text layers. Which would be preferred, to store the scores on the layers or simply have a separate function that calculates and returns the score for an inputted Text element?

**Comment by paultammo** [comment]
For the EstNLTK development version [devel_1.6](https://github.com/estnltk/estnltk/tree/devel_1.6) is the best choice. There are some [tutorials](https://github.com/estnltk/estnltk/tree/devel_1.6/tutorials) and since this branch is in active development, it is also supported in case issues arise. Alas, the installation is more complicated.

For a starting point you can use [dummy SentenceFleschScoreRetagger example](https://github.com/estnltk/estnltk/blob/devel_1.6/scribbles/sentence_flesch_score_retagger.ipynb).

**Comment by soras** [comment]
I agree with Paul that it would be the great, if you could use the version that is most actively developed. Although, this means that you have to download version [devel_1.6](https://github.com/estnltk/estnltk/tree/devel_1.6) source and build & install estnltk from the source. And there is also some extra learning to do, because API in version 1.6 is different from that in version 1.4. But if you choose this path, I'll be happy to help with any issues related to building the library or using the new API.

Using the version 1.4 is also ok. Version 1.4 does not have a common interface for Text taggers, but you can examine the code of the [Text class](https://github.com/estnltk/estnltk/blob/version_1.4/estnltk/text.py) and some existing taggers to get an idea how dependency management works and how output layers could be added. [NounPhraseChunker](https://github.com/estnltk/estnltk/blob/version_1.4/estnltk/np_chunker.py) is one example, as it works as a stand-alone tagger, not integrated as a callable from Text object.

The question about whether to calculate the score for sentences or for whole texts. Can I use sentence scores to easily calculate the score for the whole text? If not, then I would probaly prefer a method for scoring a Text object, because I can use _split_by_ method to split Text object into sentence Text objects and then calculate their scores one-by-one. Although, it would also be nice to have scores for both sentences and the text, like in Paul's example.

**Comment by kristiank** [comment]
@paultammo 

> For a starting point you can use [dummy SentenceFleschScoreRetagger example](https://github.com/estnltk/estnltk/blob/devel_1.6/scribbles/sentence_flesch_score_retagger.ipynb).

I have the latest EstNLTK installed via `conda`. I am unable to reproduce your example code. I get the following error:
```Python
sentence_flech_score_retagger.retag(text)

~/miniconda3/envs/flesch16/lib/python3.6/site-packages/estnltk/taggers/retagger.py in retag(self, text, status)
     44             This can be used to store metadata on layer creation.
     45         """
---> 46         self._change_layer(text, status)
     47         return text
     48 

TypeError: _change_layer() missing 1 required positional argument: 'status'
```

When looking at [the code for `retagger.py`](https://github.com/estnltk/estnltk/blob/devel_1.6/estnltk/taggers/retagger.py#L28) I understand I can simply give `None` as status. Is this correct?

I don't really care too much on why my installed EstNLTK code is different from the code upstreams ... probably because of me installing via `conda` and not from source.

**Comment by kristiank** [comment]
Sorry for rushing, I now understand that the `retag` in my EstNLTK 1.6.2beta installed from conda uses a signature without layers (e.g. `retag(self, text, status)` instead of `retag(slf, text, layers, status)`) but the code you posted seems to depend on `retag(slf, text, layers, status)`.

**Comment by paultammo** [comment]
My example code works with devel_1.6 branch. It has had significant changes since the latest conda install was released so the best way to make it work is to git pull devel_1.6 branch.

**Comment by kristiank** [comment]
But both branches have the same `retag ` function.
[Branch `devel_1.6`](https://github.com/estnltk/estnltk/blob/devel_1.6/estnltk/taggers/retagger.py#L28) has: 
```Python3
def retag(self, text: Text, status: dict = None, 
                check_output_consistency: bool=True ) -> Text:
```
and [branch `version_1.6`](https://github.com/estnltk/estnltk/blob/version_1.6/estnltk/taggers/retagger.py#L40) has: 
```Python3
def retag(self, text: Text, status: dict = None) -> Text:
```

**Comment by kristiank** [comment]
@paultammo I now got it working. Your naming of argument `raw_text` was a bit misleading, when I now interpret it as `text` (e.g. being of type Text) and a bit or rewriting I got it running and I think I can implement the rest by myself now. Thank you.

**Comment by kristiank** [comment]
@soras I can't find this simple thing in the tutorials: how to loop through the nested layers?

I currently try this
```Python3
text = Text("esimene lause. teine lause. kolmas pikem lause.")
text.tag_analysis()
for sentence in text.sentences.layer:
            for token in sentence.layer:
                analysises = token.get_attributes(['morph_analysis'])
                for analysis in analysises:
                    print(type(analysis))
```
The type of `analysis` is a python List. What should I do to access the analysises of a token?

**Comment by kristiank** [comment]
@soras and @paultammo what is the standard procedure to check whether a layer has been tagged/analyzed? I would like the Flesch Retagger's retag(text) to simply take a Text object as input and if the `sentences` and `morph_analysis` hasn't been done yet, it would do this by itself.

**Comment by kristiank** [comment]
I now created an initial pull request #106 for the code. I wasn't really sure where to place the code files, but maybe we can discuss that in the PR?
