### ISSUE TITLE
Build fails on Ubuntu 15.10 python3.5

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#38]
```bash
$ git branch -a
* devel
  master
```
```bash
$/usr/bin/python3.5 ./setup.py build > out.txt 2> err.txt
```
[out.txt](https://github.com/estnltk/estnltk/files/24172/out.txt)
[err.txt](https://github.com/estnltk/estnltk/files/24173/err.txt)

The first error is `estnltk/vabamorf/vabamorf_wrap.cpp:20313:1: error: too many initializers for ‘PyAsyncMethods` and results in `error: command 'g++' failed with exit status 1`

The following works as expected.
```bash
$/usr/bin/python3.4 ./setup.py build   
```

**Comment by tpetmanson** [comment]
Compiling works with latest swig devel version (3.0.8). Python3.5 is so new that the latest SWIG release (3.0.7) does not support it yet. This particular commit seems to fix our issue: https://github.com/swig/swig/commit/ef001de5240c1e05494e23b933b687f3f266045c .  

Python3.5 was released on Sep 13 2015
Swig 3.0.7 was released on Aug 4 2015.

Anyway, this problem will fix itself and we can chill and relax : D
